### ISSUE TITLE
Path Issue When Calling as a Library

### ISSUE THREAD

**Issue by SubtleMuffin** [aff3ct/cli#1]
Hi -- 

I came across path issues when calling as a library. To be specific, this happens when using the [`cython_polar` example](https://github.com/aff3ct/my_project_with_aff3ct/tree/development/examples/cython_polar), replacing the `frozen bit generator` to 5G. The 5G frozen bit generator asks `cli` to search for the path of the `.pc` file, i.e., 

```c++
cli::modify_path<cli::Is_file>("conf/cde/awgn_polar_codes/5G/N_1024.pc")
```

And below are the print outs when I add a `cout` after [L40](https://github.com/aff3ct/cli/blob/master/src/Types/File_system/File_system.hpp#L40),  

```
/Users/xxx/anaconda3/envs/yyy/bin/../../conf/cde/awgn_polar_codes/5G/N_1024.pc
/Users/xxx/anaconda3/envs/yyy/bin/../../../conf/cde/awgn_polar_codes/5G/N_1024.pc
/Users/xxx/anaconda3/envs/yyy/bin/../share/python/conf/cde/awgn_polar_codes/5G/N_1024.pc
/Users/xxx/anaconda3/envs/yyy/bin/../../share/python/conf/cde/awgn_polar_codes/5G/N_1024.pc
/usr/share/python/conf/cde/awgn_polar_codes/5G/N_1024.pc
/usr/share/python/conf/cde/awgn_polar_codes/5G/N_1024.pc
/usr/local/share/python/conf/cde/awgn_polar_codes/5G/N_1024.pc
```

Which is not ideal ... especially when it is called externally. 

Of course, one can always get around with it by implementing their own reader and generate the frozen bits, but it would be nice to consider for the sake of completeness.

**Comment by kouchy** [comment]
Hi @SubtleMuffin,

You should not use the `cli::modify_path` directly. This function is here in the case of the `conf/cde/awgn_polar_codes/5G/N_1024.pc` is not found. Then we try to check common paths and see if we can find this file elsewhere.
Check the AFF3CT factories to see how to use `cli`. Be aware that at this time `cli` is not documented at all.

Declare the parameter: https://github.com/aff3ct/aff3ct/blob/master/src/Factory/Tools/Code/Polar/Frozenbits_generator.cpp#L56-L57

`tools::add_arg` is a wrapper for AFF3CT, it is defined here: https://github.com/aff3ct/aff3ct/blob/master/src/Tools/Documentation/documentation.cpp#L181-L183

Get parameter value: https://github.com/aff3ct/aff3ct/blob/master/src/Factory/Tools/Code/Polar/Frozenbits_generator.cpp#L76

**Comment by SubtleMuffin** [comment]
Hi @kouchy ,

Thank you for your answer! I think I need to clarify my explanation. This happens when I wrap up a `Frozen bit generator 5G` function like the following, and the function is to be used with the `cython-polar` example,

```c++
auto generate_frozen_bits_5G(const int k, const int n, const float snr_max) {
  // calculate constants
  if (n > 1024) {
    std::string message = "5G frozen bits generation undefined for N > 1024";
    throw invalid_argument(__FILE__, __LINE__, __func__, message.c_str());
  }
  noise->set_noise(sigma, snr_max, esn0);

  // generate frozen bits
  std::vector<bool> frozen_bits(n);
  frozen_bits_generator.generate(frozen_bits);
  return frozen_bits;
}
```

The path issue (like the outputs above) happens when I invoke using `Python`. But, simply executing the `./bin/main`, it is able to find the `N_1024.pc`, which locates in `../../lib/conf ...`.

**Comment by kouchy** [comment]
Hi @SubtleMuffin,

I think you have the issue in Python because you are not executing the code from the same location as the main. we should add an environment variable to `cli` to look into specific locations to overcome this problem.

**Comment by kouchy** [comment]
I added a new environment variable to set the paths where `CLI` is looking for files (`AFF3CT_CLI_PATH`, see https://github.com/aff3ct/cli/commit/3dd82ab7885c3b267bae9b088d7915ca918ea8cd). Now you can manually set this variable and the Python code should work.I did not tested it on Windows, if you have the chance to do that, I would love to confirm that it is working on Windows too.

**Comment by SubtleMuffin** [comment]
@kouchy sure, I will verify on Windows and let you know in 2 days.

**Comment by SubtleMuffin** [comment]
Confirmed. Working on all three OS.
